language: node_js
node_js:
- node
install:
- npm install gulp gulp-sass
- gem install sass
- gulp sass
script:
- echo "success"
deploy:
  provider: s3
  access_key_id: AKIAJ5F5NC63TUVQILVA
  secret_access_key:
    secure: Q8+eAG70w+T6gGFhIPNvnVA7FSYwWqRDOizcgdmaReWKAL++scZKTLC3PqhX2T6qJWHxcdcFFZcKXB6Lzk533U3htwBxUgcBpxENtr7x0DwGWRxnTZ/LKRrPNDThOH81vAHflcIM2xPYlhzQqXWu9lyT68zwN/bBAzxQUcGYdwFptuXW87WLBmqmGpw2I136GVgCn1aIJWMmIHjcwu1LS8pZot3VeLdku/EB4odsFC6VtDseq/+uC3jNU19mzfSgnZhSb3rsC/N+DGyuxbci/iuI2MTZy0gEbVsleFre2cyDbXkT37doQIh6arJ5l0SvxRZy0fcT4thw+T4L5KRzV4UNP6QX8qQw6dyMTMMx7fsng4YE2Scud5K4HrCBAEE+h1zQasC2Ke2/m37l7E4IVNL8asHJbuA+gPqXESb7xK0YJdw0rOBEmlYghE3xHAvUCYe9tvJ/UvpQ+K5Jrv3wyhrPi8qlvZ6MzoRVODvX2KC5/6ddkBmvAJlb0RvGS3TGWTvKXTE0UWcns8aE6L4hufj2Q/l+XS8B0tMSukf8s5JDB8lRVxPZFoBWokjVQIJfd0e0xDigEgbIEwPIdF8SgjA2WWKlgo6cDaRHo6gA3AT/qeOX7231//t8+avEJPEvmOttGkSerGWIkdSdcDD1nlrRLdcw5rOh/nkzHm3uJsQ=
  bucket: pomodoroz.com
  local_dir: src
  skip_cleanup: true
  on:
    repo: ktadaline/Pomodoroz
    branch: master
